language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm
install:
    - composer install
#script: ./bin/phing -verbose -propertyfile build/travis.properties build-travis
script: phpunit -c build/
cache:
    directories:
        - bin/
        - build/cache/
        - build/magento/
        - vendor/
matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
